# flash-attn source build derivation.
#
# Compiles flash-attention from source against the supplied torch derivation and
# CUDA package set.  Mirrors upstream nixpkgs flash-attn/default.nix but
# substitutes our custom torch binary wheel and receives cudaPackages directly
# rather than inheriting it from torch passthru.
#
# Arguments:
#   pkgs              - nixpkgs package set; pkgs.python3 must be the target
#                       Python interpreter (set by concretise via pkgsForBuild)
#   torch             - the concrete torch derivation from resolvedDeps."torch"
#   cudaPackages      - CUDA package set (already configured for Pascal or
#                       vanilla by concretise)
#   wrappers          - retry-wrapper derivation (nvcc/gcc wrapped with retry
#                       logic); injected at the front of PATH during compilation
#   flashAttnVersion  - version string to build, e.g. "2.8.3"

{ pkgs
, torch
, cudaPackages
, flashAttnVersion
}:

let
  inherit (pkgs) lib;
  inherit (cudaPackages) backendStdenv;

  srcInfo  = import (./source-hashes + "/v${flashAttnVersion}.nix");
  srcOwner = srcInfo.owner or "Dao-AILab";
  srcRepo  = srcInfo.repo  or "flash-attention";

  # TORCH_CUDA_ARCH_LIST: semicolon-separated CUDA compute capabilities.
  # Read from cudaPackages.flags.cudaCapabilities (nixpkgs CUDA infrastructure).
  cudaCapabilities = cudaPackages.flags.cudaCapabilities;

in
pkgs.python3Packages.buildPythonPackage {
  pname   = "flash-attention";
  version = flashAttnVersion;
  pyproject = true;

  src = pkgs.fetchFromGitHub {
    owner           = srcOwner;
    repo            = srcRepo;
    tag             = srcInfo.rev;
    # hash is the NAR hash of the git clone including submodules (cutlass etc.).
    # Generated by `nix-prefetch-github --fetch-submodules`; see
    # generate-hashes/source_fetcher.py for details.
    hash            = srcInfo.hash;
    fetchSubmodules = true;
  };

  preConfigure = ''
    export MAX_JOBS="$NIX_BUILD_CORES"
    export NVCC_THREADS="$NIX_BUILD_CORES"
  '';

  env = {
    FLASH_ATTENTION_SKIP_CUDA_BUILD = "FALSE";
    CC  = "${backendStdenv.cc}/bin/cc";
    CXX = "${backendStdenv.cc}/bin/c++";
    TORCH_CUDA_ARCH_LIST = lib.concatStringsSep ";" cudaCapabilities;
  };

  build-system = [
    pkgs.python3Packages.setuptools
    pkgs.python3Packages.ninja
    pkgs.python3Packages.psutil
    cudaPackages.cuda_nvcc
  ];

  nativeBuildInputs = [
    pkgs.which
  ];

  buildInputs = with cudaPackages; [
    cuda_cccl    # <thrust/*> / <cub/*>
    libcublas    # cublas_v2.h
    libcurand    # curand.h
    libcusolver  # cusolverDn.h
    libcusparse  # cusparse.h
    cuda_cudart  # cuda_runtime.h cuda_runtime_api.h
  ];

  dependencies = [
    pkgs.python3Packages.einops
    torch
  ];

  doCheck = false;

  pythonImportsCheck = [ "flash_attn" ];

  meta = {
    description      = "Official implementation of FlashAttention and FlashAttention-2 (built from source)";
    homepage         = "https://github.com/Dao-AILab/flash-attention/";
    changelog        = "https://github.com/Dao-AILab/flash-attention/releases/tag/${srcInfo.rev}";
    license          = lib.licenses.bsd3;
    platforms        = [ "x86_64-linux" "aarch64-linux" ];
    broken           = false;
    sourceProvenance = with lib.sourceTypes; [ fromSource ];
  };
}
